hw1: main.cpp parser.c parser.h helpers.cpp executeBundles.cpp
	g++ -std=c++11 -g -o hw1 main.cpp

executeBundles: executeBundles.cpp helpers.cpp
	g++ -std=c++11 -g -o executeBundles executeBundles.cpp

deneme: deneme.cpp
	g++ -std=c++11 -g -o deneme deneme.cpp

clean:
	rm hw1